language: cpp
sudo: false
os: linux
addons:
  apt:
    packages:
    - cmake
    - time

script:
  - gcc -v && g++ -v && cmake --version
  - mkdir project/
  - cd project
  - cmake ..
  - env CTEST_OUTPUT_ON_FAILURE=1 make
  - src/main
  - ctest
