language: cpp
sudo: false
os: linux
addons:
  apt:
    packages:
    - cmake
    - time

script:
  - mkdir -p project/
  - cd project
  - cmake ..
  - make
  - env CTEST_OUTPUT_ON_FAILURE=1 ctest
  - cd ..

after_success:
  - ./travis_merge_script.sh

cache:
  directories:
    - project/googletest-download/
    - project/googletest-src/
